### PR TITLE
Implement multiview attribute

### PR DESCRIPTION
**Pull request by Ralith**

### CODE REVIEW

**Comment by Ralith** [comment]
@norru can you test this out?

**Comment by norru** [comment]
Superb! I can test this tomorrow.

**Comment by norru** [comment]
Hi, I have just tested it, by merging this change on top of master + multithread patch.

Worked at first try! Many thanks!

**Comment by Ralith** [comment]
Awesome! 

@cessen, I'd like a quick glance at the API from you before I merge this. In particular, the decision to use `impl Iterator<Item=&str>` for the getter but `&[&str]` for the setter is a judgement call. My thinking is that the setter will practically always be used with hardcoded arguments, so being able to write `Some(&["left", "right"])` is a big ergonomic win vs. taking an `IntoIterator` (since `<&[&str] as IntoIterator>::Item = &&str`). Meanwhile, the getter saves a handful of mallocs vs. `Vec<String>` and can easily be converted into that by the user if they want.

**Comment by norru** [comment]
@ralith WRT to `&[&str]`, it's exactly as said. I already have a `Vec<String>` containing the view names so borrowing a bunch of `&str` not a problem.

**Comment by Ralith** [comment]
> I already have a Vec<String> containing the view names so borrowing a bunch of &str not a problem.

I'd actually characterize that as an awkward case, since getting a `&[&str]` from a `Vec<String>` requires constructing a new vector, whereas an `Iterator<Item=&str>` does not.

**Comment by norru** [comment]
This is not an issue in my use case and I find passing a slice more
intuitive than passing an iterator.

This is unlikely to give any kind of performance hit in practical cases.
However it's up to you :)

**Comment by cessen** [comment]
@Ralith 
The API looks good to me!  Like you say, I expect most cases will be hard-coded, and even those that aren't are unlikely to be large or especially awkward to construct `Vec`s for.  If this turns out not to be the case in the future, or if we change our mind based on future custom attribute APIs, I don't think it's the end of the world to come back and change this.

**Pull request merged**
