### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Ralith**
I've restructured both levels of the library to reduce mismatch between the foreign code and the rust API in the spirit of #2. Since my proximate need is for decoding, I haven't made an effort to rework the encoding side of things.

Do these changes seem reasonable to you?

### CODE REVIEW

**Comment by cessen** [comment]
Oh man, thanks so much!  This looks great.  No worries about file writing, I'll add that back in when I get the chance (the project I have that uses this lib points at a particular commit, so there's no rush from my perspective).

Do you plan to continue contributing, btw?  If so, I might put this up on crates.io.  I was hesitant before because it was just me with only one use-case for the lib.  But if both of us are working on it and you also have a use-case to validate against, I'm more confident that this won't just die in the wind or have an overly specific API design.

**Comment by Ralith** [comment]
I expect to be relying on this library for the foreseeable future, and I'll at least be contributing as necessary to support my (game-related) use case. So, yes, I expect to continue to contribute to maintenance at least, though I probably won't be filling in a ton of new API surface area, especially once basic writing is supported.

I was actually thinking about putting in some more effort to get ahold of you and ask for permission to publish myself if you didn't resurface soon, since even the tiny API surface exposed by this PR seems likely to be useful to anyone who needs to consume HDR content. OpenEXR has an intimidating amount of surface area but you can do an awful lot of neat stuff with only the very basics.

**Comment by abusch** [comment]
Hi, I'm just some random passer-by, but I've been keeping an eye on this project as I'll need basic EXR read support for a project of mine, so it's great to see it move forward! It'd be awesome if this was published to crates.io at some point.

**Comment by cessen** [comment]
Hi Abusch,
It's now on crates.io!  I changed the build.rs in openexr-sys before publishing to hopefully make it more flexible, so if you want to try using openexr-rs in a test project just to make sure it builds for you that would be really helpful!  If you have any troubles, please file an issue and I'll take a look the next chance I get.  Only if you have the time, of course.

**Comment by abusch** [comment]
Awesome, I'll give it a shot!

**Pull request merged**
